### ISSUE TITLE
common_types not implemented

### ISSUE THREAD

**Issue by DaKnig** [Siriusmart/invidious-rs#15]
instead of having many different Video structs like ChannelVideo, have one unified common Video type. same for playlists, thumbnails etc.
https://docs.invidious.io/api/common_types/

**Comment by Siriusmart** [comment]
working on it

most

**Comment by DaKnig** [comment]
imho you should just have separate Video and CommonVideo or ShortVideo or w.e

**Comment by DaKnig** [comment]
having access to fields is super cool. or at least provide methods.

**Comment by Siriusmart** [comment]
168 additions and 342 deletions ive switched types to use the shared common structs if possible

i still have not impled the from functions, but im gonna add them along with other utility functions later just because i can

**Comment by Siriusmart** [comment]
its on crates.io, i havent added the uitility functions yet
