### ISSUE TITLE
ClientAsync is not Clone

### ISSUE THREAD

**Issue by DaKnig** [Siriusmart/invidious-rs#3]
Despite looking like ClientSync, it is not Clone.

**Comment by DaKnig** [comment]
consider the following code: 
```
            let vid_data =
                self.invidious_client.borrow().video(&vid_id, None).await;
```
from my repo. in my case `self.invidious_client` is a `RefCell<ClientAsync>`, and this code invokes the clippy msg "borrow across await!" or so. in the future I want to add the ability to change this property on the fly, from settings or maybe dynamically choose the instance or something. it would make sense to clone this object (not that expensive) and then await that

**Comment by DaKnig** [comment]
> Yes, that's because `ClientAsync` contains `MethodAsync`, which can contains _a custom method_ (`Box<dyn Fn(String) -> Pin<Box<dyn Future<Output = MethodReturn> + Send>> + Send + Sync>`) I couldn't make it clone.
> 
> So either I figure out how to make that clone, or maybe I will include an ClientAsyncClone struct which does not allow custom method.
how about making it a trait with a few implementers? a invidious::MethodAsync::Preset would implement it, but also Custom, then the first would be Clone and the second would not. the trait would not need to require Clone...

**Comment by Siriusmart** [comment]
So you would suggest doing something like

- Having `ClientSyncTrait` and `ClientAsyncTrait`
- `ClientSync` and `ClientAsync` impls the traits respectively

It's not that hard, I can do that.

**Comment by Siriusmart** [comment]
I've done it, `ClientAsync` is now Clone.

Bump the version up `0.6.0`->`0.6.1`, unless you are using custom methods the code should just work.

Hope that helps.

**Comment by Siriusmart** [comment]
Using traits allows clients to be able to have custom fetch methods *and* be able to clone, which is really cool.

Also added `ClientAsyncClone` as a subset of `ClientAsyncTrait`

**Comment by DaKnig** [comment]
not sure how useful `ClientAsyncClone` is, its just `ClientAsyncTrait + Clone`, which would be more readable
