### ISSUE TITLE
Can't fetch a particular playlist

### ISSUE THREAD

**Issue by matous-volf** [Siriusmart/invidious-rs#6]
Hi, I'm unable to fetch data about this playlist:
https://www.youtube.com/playlist?list=OLAK5uy_kciTzXJBH4KscvdNJrW3FtCO6kInaZxgo
Other playlists work fine. Maybe it's the different ID lenght that is causing this?

My code:
```rs
use invidious::*;

#[tokio::main]
async fn main() {
    let client = ClientAsync::default();
    let playlist = client.playlist("OLAK5uy_kciTzXJBH4KscvdNJrW3FtCO6kInaZxgo", None).await;
    dbg!(playlist);
}
```

The output:
```
[src/main.rs:8] playlist = Err(
    Error("invalid type: null, expected a string", line: 0, column: 0),
)
```

**Comment by Siriusmart** [comment]
![image](https://github.com/Siriusmart/invidious-rs/assets/71584876/94f7ea47-0cbb-40c3-a896-1e2c2aed94a8)
your playlist thumbnail is null for some reason

i'll just throw in `#[serde(default)]` in everything, its so weird

**Comment by Siriusmart** [comment]
Ok I found a better solution, grab the thumbnail from the first video and transplant it to the playlist thumbnail field.

Check the latest git commit to see if it works.

```toml
invidious = { git = "https://github.com/siriusmart/invidious", rev = "30cc312" }

**Comment by matous-volf** [comment]
It does indeed work. Will you publish a release?
By the way, your username in the git URL should start with a capital S, otherwise it's 404.

**Comment by Siriusmart** [comment]
np im publishing it

**Comment by Siriusmart** [comment]
published
